listen_addr: ":8080"

crypto:
  - id: "default"
    layers:
      - algorithm: "tink"
        keyset:
          env_var: "TINK_KEYSET"
  - id: "default-triple"
    layers:
      - algorithm: "chacha20poly1305"
        keyset:
          env_var: "CHACHA_KEY"
      - algorithm: "aes"
        keyset:
          env_var: "AES_KEY"
        params:
          mode: "gcm"
      - algorithm: "tink"
        keyset:
          env_var: "TINK_KEYSET"

s3_clients:
  - id: "local"
    endpoint: "http://localhost:9000"
    region: "us-east-1"
    access_key:
      env_var: "S3_ACCESS_KEY"
    secret_key:
      env_var: "S3_SECRET_KEY"

s3_buckets:
  - bucket_name: "test-bucket"
    backends:
      - s3_client_id: "local"
        s3_bucket_name: "test-bucket"
        crypto_id: "default"

  - bucket_name: "test-bucket1"
    backends:
      - s3_client_id: "local"
        s3_bucket_name: "test-bucket"
        crypto_id: "default-triple"
auth:
  users:
    - access_key:
        env_var: "ALLOWED_ACCESS_KEY1"
    - access_key:
        env_var: "ALLOWED_ACCESS_KEY2"
