# configs/main.yaml

listen_addr: ":8080"

crypto:
  - id: "default"
    layers:
      - algorithm: "tink"
        keyset:
          data: ""

s3_clients:
  - id: "local"
    endpoint: "http://localhost:9000"
    region: "us-east-1"
    access_key:
      data: "minioadmin"
    secret_key:
      data: "minioadmin"

s3_buckets:
  - bucket_name: "test-bucket"
    backends:
      - s3_client_id: "local"
        s3_bucket_name: "test-bucket"
        crypto_id: "default"
