# configs/main.yaml

listen_addr: ":8080"

crypto:
  - id: "default"
    layers:
      - algorithm: "tink"
        keyset:
          data: "eyJwcmltYXJ5S2V5SWQiOjQ1NzY1NTYzMywgImtleSI6W3sia2V5RGF0YSI6eyJ0eXBlVXJsIjoidHlwZS5nb29nbGVhcGlzLmNvbS9nb29nbGUuY3J5cHRvLnRpbmsuQWVzR2NtS2V5IiwgInZhbHVlIjoiR2lBZ0xYQjhpS1hIZDZEWXQzSVdXdTEvaU9LeVUybEZBZXpTc2Y0NVhOeWZaUT09IiwgImtleU1hdGVyaWFsVHlwZSI6IlNZTU1FVFJJQyJ9LCAic3RhdHVzIjoiRU5BQkxFRCIsICJrZXlJZCI6NDU3NjU1NjMzLCAib3V0cHV0UHJlZml4VHlwZSI6IlRJTksifV19"

s3_clients:
  - id: "local"
    endpoint: "http://localhost:9000"
    region: "us-east-1"
    access_key:
      data: "minioadmin"
    secret_key:
      data: "minioadmin"

s3_buckets:
  - bucket_name: "test-bucket"
    backends:
      - s3_client_id: "local"
        s3_bucket_name: "test-bucket"
        crypto_id: "default"
