# configs/main.yaml

listen_addr: ":8080"

crypto:
  - id: "default"
    layers:
      - algorithm: "tink"
        keyset:
          data: "eyJwcmltYXJ5S2V5SWQiOjQyMDgxODQ4MjksICJrZXkiOlt7ImtleURhdGEiOnsidHlwZVVybCI6InR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLmNyeXB0by50aW5rLkFlc0djbUtleSIsICJ2YWx1ZSI6IkdpQit2bTZHRlZ5OW03aGNZQXByZUZzSDFoR2hRamsyNlpaQU9ndlh0RTJVcmc9PSIsICJrZXlNYXRlcmlhbFR5cGUiOiJTWU1NRVRSSUMifSwgInN0YXR1cyI6IkVOQUJMRUQiLCAia2V5SWQiOjQyMDgxODQ4MjksICJvdXRwdXRQcmVmaXhUeXBlIjoiVElOSyJ9XX0="

s3_clients:
  - id: "local"
    endpoint: "http://localhost:9000"
    region: "us-east-1"
    access_key:
      data: "minioadmin"
    secret_key:
      data: "minioadmin"

s3_buckets:
  - bucket_name: "test-bucket"
    backends:
      - s3_client_id: "local"
        s3_bucket_name: "test-bucket"
        crypto_id: "default"
